apiVersion: v1
kind: Pod
metadata:
  name: hello-world-pod
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: writer
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["while true; do echo '$(date) - Hello from writer container!' >> /data/message.txt; sleep 1; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /data
    - name: reader
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["while true; do cat /data/message.txt; sleep 1; done"]
      volumeMounts:
        - name: shared-data
          mountPath: /data