apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
spec:
  containers:
  - name: redis-pod
    image: redis
    volumeMounts:
    - name: credentials
      mountPath: "/etc/creds"
      readOnly: true
  volumes:
  - name: credentials
    secret:
      secretName: db-user-pass
      optional: true