apiVersion: v1
kind: Pod
metadata:
  name: app-env
spec:
  containers:
  - name: main-container
    image: nginx
    env:
    - name: MODE
      value: "dev"
    - name: PROXY_URL
      value: "proxy.local"
